# Generated by Django 5.2.4 on 2025-07-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_evento', models.CharField(choices=[('15', 'Fiesta de 15'), ('boda', 'Casamiento')], max_length=20)),
                ('fecha_evento', models.DateField()),
            ],
        ),
    ]
