# Generated by Django 5.2.4 on 2025-07-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_vestimenta',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_evento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='hora_evento',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='imagen5',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='imagen6',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='imagen7',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='imagen8',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='lugar_evento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='mensaje_bienvenida',
            field=models.TextField(blank=True),
        ),
    ]
