# Generated by Django 5.2.4 on 2025-07-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_codigo_vestimenta_cliente_direccion_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagen_fondo',
            field=models.ImageField(blank=True, null=True, upload_to='fondos/'),
        ),
    ]
