# Generated by Django 5.2.4 on 2025-07-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente_instagram_url_cliente_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='titulo',
            field=models.TextField(),
        ),
    ]
