# Generated by Django 5.2.4 on 2025-07-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cliente_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
