# Generated by Django 5.2.4 on 2025-07-26 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cliente_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_evento',
            field=models.CharField(choices=[('15', 'Fiesta de 15'), ('boda', 'Casamiento'), ('cumple', 'Cumpleaños'), ('otros', 'Otros')], max_length=20),
        ),
        migrations.CreateModel(
            name='ConfirmacionAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_invitado', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('asistencia', models.BooleanField()),
                ('fecha_confirmacion', models.DateTimeField(auto_now_add=True)),
                ('cantidad_acompanantes', models.PositiveIntegerField(default=0)),
                ('restricciones_alimentarias', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones', to='core.cliente')),
            ],
        ),
    ]
