# Generated by Django 5.2.4 on 2025-07-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cliente_tipo_evento_confirmacionasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='token_acceso',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
