# Generated by Django 5.2.4 on 2025-07-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cliente_token_acceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacionasistencia',
            name='cantidad_acompanantes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
