# Generated by Django 5.2.4 on 2025-07-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_confirmacionasistencia_cantidad_acompanantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacionasistencia',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='confirmacionasistencia',
            name='telefono_envio_confirmacion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='confirmacionasistencia',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
