# Generated by Django 5.2.4 on 2025-07-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_confirmacionasistencia_telefono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmacionasistencia',
            name='telefono_envio_confirmacion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_envio_confirmacion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
