# Generated by Django 5.2.4 on 2025-07-29 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_confirmacionasistencia_telefono_envio_confirmacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancionPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_interprete', models.CharField(max_length=100)),
                ('nombre_tema', models.CharField(max_length=200)),
                ('fecha_sugerencia', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='core.cliente')),
            ],
            options={
                'ordering': ['-fecha_sugerencia'],
            },
        ),
    ]
