# Generated by Django 5.2.4 on 2025-07-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cancionplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='alias_regalos',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
