# Generated by Django 5.2.4 on 2025-07-31 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.template'),
        ),
    ]
