# Generated by Django 5.2.4 on 2025-08-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cliente_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagen9',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='imagen_fondo_ig',
            field=models.ImageField(blank=True, null=True, upload_to='fondos/'),
        ),
    ]
