# Generated by Django 5.2.4 on 2025-08-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cliente_imagen9_cliente_imagen_fondo_ig'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fuente_nombre',
            field=models.CharField(choices=[('Great Vibes', 'Great Vibes'), ('Dancing Script', 'Dancing Script'), ('Allura', 'Allura'), ('Sacramento', 'Sacramento'), ('Parisienne', 'Parisienne')], default='Great Vibes', max_length=50),
        ),
    ]
