# Generated by Django 5.2.4 on 2025-08-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cliente_fuente_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='hora_evento',
            field=models.TimeField(),
        ),
    ]
