# Generated by Django 5.2.4 on 2025-08-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_cliente_hora_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_evento',
            field=models.CharField(choices=[('15', 'Fiesta de 15'), ('boda', 'Casamiento'), ('cumple', 'Cumpleaños'), ('otros', 'Otros'), ('infantil', 'Infantil')], max_length=20),
        ),
    ]
