# Generated by Django 5.2.4 on 2025-09-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_cliente_tipo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fuente_nombre',
            field=models.CharField(choices=[('Great+Vibes', 'Great Vibes'), ('Dancing+Script', 'Dancing Script'), ('Allura', 'Allura'), ('Sacramento', 'Sacramento'), ('Parisienne', 'Parisienne')], default='Great Vibes', max_length=50),
        ),
    ]
